version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: caxora-postgres
    environment:
      POSTGRES_DB: CaxoraDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: caxora123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: caxora-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@caxora.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
